########################
# NODES
########################

# Defined in alphabetical order

short mutation:
    is_a: sequence variant
    represented_as: node
    label_in_input: short_mutation
    properties:
        citation_PM_ids: str
        consequence: str
        homogenous: str
        mutation_effect_description: str
        data_source: str
        oncogenic: str
        reference_genome: str
        tumor_type: str
        tumor_type_summary: str
        variant_summary: str
        # ensembl_id_alteration: str

copy number amplification:
    is_a: sequence variant
    represented_as: node
    label_in_input: copy_number_amplification
    properties:
        citation_PM_ids: str
        consequence: str
        homogenous: str
        mutation_effect_description: str
        data_source: str
        oncogenic: str
        reference_genome: str
        tumor_type: str
        tumor_type_summary: str
        variant_summary: str
        # ensembl_id_alteration: str

structural variant:
    is_a: sequence variant
    represented_as: node
    label_in_input: structural_variant
    properties:
        citation_PM_ids: str
        consequence: str
        homogenous: str
        mutation_effect_description: str
        data_source: str
        oncogenic: str
        reference_genome: str
        tumor_type: str
        tumor_type_summary: str
        variant_summary: str
        # ensembl_id_alteration: str

disease:
    represented_as: node
    label_in_input: disease
    properties:
        data_source: str

gene status:
    is_a: outcome
    represented_as: node
    label_in_input: gene_status
    properties:
        data_source: str
        gene_symbol_gene_status: str
        gene_role: str

source gene:
    is_a: gene
    represented_as: node
    label_in_input: source_gene
    properties:
        gene_symbol: str
        gene_summary: str
        data_source: str

target gene:
    is_a: gene
    represented_as: node
    label_in_input: target_gene
    properties:
        gene_symbol: str
        gene_summary: str
        data_source: str

gene:
    represented_as: node
    label_in_input: gene
    properties:
        gene_symbol: str
        gene_summary: str # DECIDER
        name: str # OT
        data_source: str

patient:
    represented_as: node
    label_in_input: patient
    synonym_for: case
    properties:
        survival: str
        treatment_strategy: str
        data_source: str

sample:
    is_a: material sample
    respresented_as: node
    label_in_input: sample
    properties:
        data_source: str

# Drug

row_drug:
    is_a: drug 
    represented_as: node
    label_in_input : row_drug
    properties:
        canonicalSmiles: str
        inchiKey: str
        drugType: str
        blackBoxWarning: bool
        drug_name: str
        yearOfFirstapproval: str
        maximumClinicalTrialPhase: str
        hasBeenWithdrawn: bool
        isApproved: bool
        tradeName: str
        synonym: str
        references: str
        description: str
        data_source: str

drug:
    represented_as: node
    input_label: drug # final_type node type
    properties:
        name: str
        ncbi_tax_id: str
        canonicalSmiles: str
        inchiKey: str
        drugType: str
        blackBoxWarning: bool
        drug_name: str
        yearOfFirstapproval: str
        maximumClinicalTrialPhase: str
        hasBeenWithdrawn: bool
        isApproved: bool
        tradeName: str
        synonym: str
        references: str
        description: str
        data_source: str

# Long non Coding - RNA

lncrna:
    is_a: noncoding RNA product
    represented_as: node
    input_label: lncrna
    properties:
        name: str
        ncbi_tax_id: str

# Macromolecular complex

source complex:
    is_a: macromolecular_complex
    represented_as: node
    input_label: source_complex
    properties:
        name: str
        ncbi_tax_id: str

target complex:
    is_a: macromolecular_complex
    represented_as: node
    input_label: target_complex
    properties:
        name: str
        ncbi_tax_id: str

macromolecular complex:
    represented_as: node
    input_label: macromolecular_complex 
    properties:
        name: str
        ncbi_tax_id: str

# Micro-RNA

mirna:
    is_a: microRNA
    represented_as: node
    input_label: mirna
    properties:
        name: str
        ncbi_tax_id: str

# Protein

source protein:
    is_a: protein
    represented_as: node
    input_label: source_protein
    properties:
        ensembl_gene_id: str
        gene_symbol: str
        ncbi_tax_id: str
        data_source: str

target protein:
    is_a: protein
    represented_as: node
    input_label: target_protein
    properties:
        ensembl_gene_id: str
        gene_symbol: str
        ncbi_tax_id: str
        data_source: str

protein:
    represented_as: node
    input_label: protein
    properties:
        ensembl_gene_id: str
        gene_symbol: str
        ncbi_tax_id: str
        data_source: str

# Treatment

treatment:
    represented_as: node
    input_label: treatment

########################
# EDGES
########################

## CAUSAL LINKS
## Everything that derivates from the "causes" link type.
## Comprises both real causes and ownership ("carries").

### CARRIES

# To allow queries for patient carrying samples, and samples carrying variants,
# without mixing with "effects" causes.
carries:
    is_a: causes
    represented_as: edge
    label_in_input: carries
    properties:
        data_source: str
        edglelabel: str

patient carries sample:
    is_a: carries
    represented_as: edge
    label_in_input: patient_carries_sample
    source: patient
    target: sample
    properties:
        data_source: str
        edglelabel: str

sample carries variant:
    is_a: carries
    represented_as: edge
    label_in_input: sample_carries_variant
    source: sample
    target: sequence variant
    properties:
        refCount: int64
        altCount: int64
        expressed: bool
        homogenous: bool
        data_source: str
        edglelabel: str


### CAUSES

# A gene is linked to its gene status (gain or loss of function),
# which are represented as nodes, so as to allow a causal path
# to go through variant -> gene status -> transcript activity.
# Hence, outcomes have at least two instances:
# - Gene:GoF, and
# - Gene:LoF.

variant causes gene status:
    is_a: causes
    represented_as: edge
    label_in_input: variant_causes_gene_status
    source: sequence variant
    target: gene status
    properties:
        data_source: str
        edglelabel: str

### BIOMARKER

# In some databases, such as OncoKB, drugs are associated with variants
# as predictive markers for treatment response, 
# based on clinical evidence categorized by evidence levels. 

variant biomarker for treatment:
    is_a: sequence variant modulates treatment association
    represented_as: edge
    label_in_input: variant_biomarker_for_treatment
    source: sequence variant
    target: treatment
    properties:
        level_of_evidence: str
        cgi_level: str
        citations: str
        tumorType: str
        data_source: str
        edglelabel: str

## METADATA

patient has chronic illness:
    is_a: entity to disease association
    represented_as: edge
    label_in_input: patient_has_chronic_illness
    source: patient
    target: disease
    properties:
        data_source: str

### AFFECTS

gene status affects gene:
    is_a: affects
    represented_as: edge
    label_in_input: gene_status_affects_gene
    source: gene status
    target: gene
    properties:
        data_source: str
        edglelabel: str


### GO -- TO BE FIXED

biological process:
    is_a: named thing
    represneted_as: node
    label_in_input: biological_process
    properties:
        data_source: str

gene to biological process:
    is_a: association
    represented_as: edge
    label_in_input: gene_to_biological_process
    source: gene
    target: biological process
    properties:
        edglelabel: str
        data_source: str

biological process to gene:
    is_a: association
    represented_as: edge
    label_in_input: biological_process_to_gene
    source: biological process
    target: gene
    properties:
        data_source: str

### FUNCTIONAL PROTEIN PROTEIN INTERACTIONS

undirected molecular interaction:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: undirected_molecular_interaction
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: str
        extra_attrs: str
        evidences: str

stimulation:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: stimulation
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: str
        extra_attrs: str
        evidences: str

inhibition:
    is_a: pairwise molecular interaction
    represented_as: edge
    input_label: inhibition
    properties:
        is_directed: bool
        is_stimulation: bool
        is_inhibition: bool
        consensus_direction: bool
        consensus_stimulation: bool
        consensus_inhibition: bool
        sources: str
        references: str
        omnipath: bool
        kinaseextra: bool
        ligrecextra: bool
        pathwayextra: bool
        dorothea: bool
        collectri: bool
        tf_target: bool
        lncrna_mrna: bool
        tf_mirna: bool
        small_molecule: bool
        dorothea_curated: bool
        dorothea_chipseq: bool
        dorothea_tfbs: bool
        dorothea_coexp: bool
        dorothea_level: str
        type: str
        curation_effort: str
        extra_attrs: str
        evidences: str

### TRASNCRIPT TO GENE RELATIONSHIP

transcript to gene relationship:
    # is_a: transcript to gene relationship
    represented_as: edge
    input_label: transcript_to_gene_relationship
    properties:
        data_source: str

### DRUG HAS TARGET

drug has target:
    is_a: drug to gene association
    represented_as: edge
    label_in_input: drug_has_target
    properties:
        data_source: str

treatment has part drug:
    is_a: association
    represented_as: edge
    label_in_input: treatment_has_part_drug
    properties:
        data_source: str

