#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi



# Check if the diff contains patient code-like strings.
test=$(GIT_CONFIG_GLOBAL='' git diff --cached HEAD | grep -e '\<[A-Z][0-9]\{3\}\>')
if [ "$test" != "" ] ; then
	cat <<\EOF
ERROR: I detected patient H-code-like strings in the diff of this commit.
I will forbid any such commit.
Please double check for strings matching '\<[A-Z][0-9]\{3\}\>'.
If you're sure there's no leaking data, you may commit with: git --no-verify commit …
EOF
	exit 1
fi
